lightgbm:
  one_hot: False
  tuning: bayesian
  fixed_params:
    device: cpu
    boosting_type: gbdt
    metric: l2
    early_stopping_rounds: 100
  tuned_params:
    n_estimators: (1, 8000)
    learning_rate: (1e-8, 1e-1)
    num_leaves: (1, 6000)
    max_depth: (1, 20)
    feature_fraction: [0.9, 1.0]
    num_iterations: (1, 200)
    max_bin: (200, 300)
  tunesearch:
    early_stopping: True
    n_trials: 1000
    max_iters: 10
    search_optimization: "bayesian"
    use_gpu: True
    verbose: 1
